server:
  port:
  context-path:
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host:
    timeout:
    port:
datasource:
  shop:
    jdbcUrl:
    username:
    password:
    maximumPoolSize:
  admin:
    jdbcUrl:
    username:
    password:
    maximumPoolSize:
qiniuyun:
  oss:
    accessKeyId:
    accessKeySecret:
    bucketName:
pagehelper:
  auto-dialect:
  helper-dialect:
  page-size-zero:
alipay:
  # 支付宝网关名、partnerId和appId
  openApiDomain :
  mcloudApiDomain :
  pid :
  appid :
  # RSA私钥、公钥和支付宝公钥
  privateKey :
  publicKey :
  #SHA1withRsa对应支付宝公钥
  #alipay_public_key ：
  #SHA256withRsa对应支付宝公钥
  alipayPublicKey :
  # 签名类型: RSA->SHA1withRsa,RSA2->SHA256withRsa
  signType : RSA2
  # 当面付最大查询次数和查询间隔（毫秒）
  maxQueryRetry : 5
  queryDuration : 5000
  # 当面付最大撤销次数和撤销间隔（毫秒）
  maxCancelRetry : 3
  cancelDuration : 2000
  # 交易保障线程第一次调度延迟和调度间隔（秒）
  heartbeatDelay : 5
  heartbeatDuration : 900